services:
  - type: web
    name: agriconnect
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn agriconnect_project.wsgi:application"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
