# Generated by Django 6.0.5 on 2026-07-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('demand_level', models.CharField(default='Medium', max_length=20)),
                ('forecast_direction', models.CharField(default='Stable', max_length=20)),
                ('region', models.CharField(default='Rajkot, Gujarat', max_length=100)),
                ('volume_tonnes', models.IntegerField(default=120)),
                ('record_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.category')),
            ],
        ),
    ]
