# Generated by Django 6.0.5 on 2026-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_order_status_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order', 'Order Update'), ('price', 'Price Alert'), ('weather', 'Weather Alert'), ('system', 'System Announcement'), ('message', 'Chat Message'), ('review', 'Customer Review'), ('product', 'Product Status'), ('verification', 'Document Verification')], default='system', max_length=20),
        ),
    ]
