# Generated by Django 5.2.16 on 2026-08-12 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='harvest_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='crop',
            name='shelf_life_days',
            field=models.IntegerField(default=30),
        ),
    ]
