# Generated by Django 5.2.16 on 2026-09-14 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage fee taken by platform per order', max_digits=5)),
                ('default_delivery_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('contact_email', models.EmailField(default='support@agriconnect.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1234567890', max_length=20)),
                ('is_maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ticket_type',
            field=models.CharField(choices=[('Order Issue', 'Order Issue'), ('Product Quality Issue', 'Product Quality Issue'), ('Delivery Issue', 'Delivery Issue'), ('Farmer Complaint', 'Farmer Complaint'), ('Buyer Complaint', 'Buyer Complaint')], default='Order Issue', max_length=50),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('target_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
