# Generated by Django 5.2.16 on 2026-09-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_buyer_favorite_farmers'),
        ('marketplace', '0013_systemsettings_feedback_status_feedback_ticket_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactivitylog',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.RemoveField(
            model_name='farmerrating',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='farmerrating',
            name='farmer',
        ),
        migrations.AlterUniqueTogether(
            name='favoritefarmer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoritefarmer',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='favoritefarmer',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketinsight',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderotp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderstatushistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pricetrend',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.AddField(
            model_name='crop',
            name='current_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_demand_level',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_forecast_direction',
            field=models.CharField(default='Stable', max_length=20),
        ),
        migrations.AddField(
            model_name='crop',
            name='market_price_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crop',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='return_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged Product'), ('wrong', 'Wrong Product'), ('quality', 'Quality Issue'), ('late', 'Late Delivery'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='current_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='market_demand_level',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='market_forecast_direction',
            field=models.CharField(default='Stable', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='market_price_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='delivery_rating',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.farmer'),
        ),
        migrations.AddField(
            model_name='review',
            name='packaging_rating',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='quality_rating',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.crop'),
        ),
        migrations.DeleteModel(
            name='AdminActivityLog',
        ),
        migrations.DeleteModel(
            name='FarmerRating',
        ),
        migrations.DeleteModel(
            name='FavoriteFarmer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='MarketInsight',
        ),
        migrations.DeleteModel(
            name='OrderOTP',
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.DeleteModel(
            name='PriceTrend',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
