# Generated by Django 5.2.16 on 2026-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_remove_adminactivitylog_admin_user_delete_emaillog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='current_market_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='market_demand_level',
        ),
        migrations.RemoveField(
            model_name='order',
            name='market_forecast_direction',
        ),
        migrations.RemoveField(
            model_name='order',
            name='market_price_history',
        ),
        migrations.AddField(
            model_name='order',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('damaged', 'Damaged Product'), ('wrong', 'Wrong Product'), ('quality', 'Quality Issue'), ('late', 'Late Delivery'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
