# Generated by Django 5.2.16 on 2026-09-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_orderotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteFarmer',
        ),
    ]
