# Generated by Django 5.2.16 on 2026-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Product Rating'),
        ),
    ]
