# Generated by Django 6.0.5 on 2026-07-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='experience',
            field=models.CharField(default='5 Years', max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='orders_completed',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='specialization',
            field=models.CharField(default='General Farming', max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='store_rating',
            field=models.FloatField(default=4.5),
        ),
    ]
