# Generated by Django 6.0.5 on 2026-07-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_farmer_about_farmer_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='cover_banner',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='ontime_delivery',
            field=models.IntegerField(default=98),
        ),
        migrations.AddField(
            model_name='farmer',
            name='repeat_customers',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='farmer',
            name='satisfaction_rate',
            field=models.IntegerField(default=97),
        ),
    ]
