# Generated by Django 6.0.5 on 2026-07-12 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmer_awards_farmer_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='aadhaar_document',
            field=models.FileField(blank=True, null=True, upload_to='farmer_docs/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='approval_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_certificate',
            field=models.FileField(blank=True, null=True, upload_to='farmer_docs/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='trust_score',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='farmer',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Submission'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmission Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_farmers', to=settings.AUTH_USER_MODEL),
        ),
    ]
