# Generated by Django 6.0.5 on 2026-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmer_aadhaar_document_farmer_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='organic_certificate',
            field=models.FileField(blank=True, null=True, upload_to='farmer_docs/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
