# Generated by Django 5.2.16 on 2026-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='favorite_farmers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='accounts.farmer'),
        ),
    ]
